name: Reusable Workflow To Deploy MuleSoft Application
 
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
 
     # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    #   # Step 3: Set up Maven
    # - name: Set up Maven
    #   uses: actions/setup-java@v3
    #   with:
    #     maven-version: '3.8.7'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - name: Upload artifact 
      uses: actions/upload-artifact@v3
      with:
          name: artifacts
          path: target/*.jar


          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      CONNECTED_APP_CLIENT_SECRET: ${{ CONNECTED_APP_CLIENT_SECRET }}
      ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
      ANYPOINT_ENV: ${{ secrets.ANYPOINT_ENVIRONMENT_ID }}
      ANYPOINT_PRIVATE_SPACE_ID: ${{ secrets.ANYPOINT_PRIVATE_SPACE_ID }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Install Anypoint CLI
      run: |
        curl -L https://anypoint.mulesoft.com/downloads/cli/anypoint-cli-linux-64.zip -o anypoint-cli.zip
        unzip anypoint-cli.zip -d anypoint-cli
        sudo mv anypoint-cli/bin/anypoint-cli /usr/local/bin/

    - name: Authenticate with Anypoint
      run: |
        anypoint-cli --username="$CONNECTED_APP_CLIENT_ID" --password="$CONNECTED_APP_CLIENT_SECRET" --organization="$ANYPOINT_ORG_ID" --environment="$ANYPOINT_ENVIRONMENT_ID" login

    - name: Deploy Application to Private Space
      run: |
        anypoint-cli runtime-mgr cloudhub-application deploy \
          --name="demo_deploy" \
          --region="us-east-1" \
          --workers=1 \
          --workerType="Micro" \
          --private-space-id="$ANYPOINT_PRIVATE_SPACE_ID"
